# Generated by Django 6.0.6 on 2026-06-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='store_produ_id_2abda1_idx',
            old_name='store_produ_id_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='store_produ_name_5e57da_idx',
            old_name='store_produ_name_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='store_produ_created_ca958a_idx',
            old_name='store_produ_created_idx',
        ),
    ]
